### ISSUE TITLE
#

### ISSUE THREAD

**Issue by Anleeno-Xu** [bubbliiiing/mobilenet-yolov4-lite-pytorch#12]
#

**Comment by bubbliiiing** [comment]
你的机子配置是不是非常好。
我这里gpu和cpu都是快满的。
正是因为轻量级的库才没法填满好的cpu和卡吧。

**Comment by bubbliiiing** [comment]
而且和你的存储盘也有关系

**Comment by Anleeno-Xu** [comment]
@bubbliiiing 
![image](https://user-images.githubusercontent.com/41414217/120962693-d0f80580-c792-11eb-92c7-5cff2b41564a.png)
![image](https://user-images.githubusercontent.com/41414217/120962713-dce3c780-c792-11eb-82a2-dc411c6f74b6.png)
这是batchsize=128 / 64的, 这个损失曲线正常吗，mobilenetv2的，载入预训练权重在voc上训练。
smooth是为了防止曲线上下波动不好看加的吧，但我好像做了很多实验（batchsize=32 / 16）发现损失就是非常稳地逐步下降至收敛，归一化大概2.5，不归一大概6.2，epoch=200，然后在收敛的loss有0.01~0.1的波动幅度，不知道作者的损失是不是这样

**Comment by bubbliiiing** [comment]
可以看出来你的电脑真的很好0 0
loss看起来算正常，但是要看数据集。
voc的话最后不归一化6.2是对的
