### ISSUE TITLE
路径参数设置都没有问题，输入图片的大小为200x200。训练时可以正常训练，测试时出现如下图的错误

### ISSUE THREAD

**Issue by linge00** [bubbliiiing/mobilenet-yolov4-lite-pytorch#19]
![image](https://user-images.githubusercontent.com/73591996/142814266-48106148-0df5-4b9f-b77b-9ab15c43f711.png)

**Comment by linge00** [comment]
还有对于这种输入200x200的图像怎么处理

**Comment by linge00** [comment]
参数设置有问题

**Comment by bubbliiiing** [comment]
classes_path
