### ISSUE TITLE
请问大神这个三模型训练的时候是否先在coco上预训练后再去VOC上训练的？

### ISSUE THREAD

**Issue by zhahuwangking** [bubbliiiing/mobilenet-yolov4-lite-pytorch#4]
问题1：如题。
问题2：keras版本的效果为什么比pytorch版本的效果好？
问题3：使用解冻训练的时候反而效果会变差，一般会是什么原因呢？
（PS：大神最高！！！！）

**Comment by bubbliiiing** [comment]
1我训练的时候只用了voc12+07
2我也挺想知道的，我归结于keras的imagenet预训练权重更好
3可能是因为提取到的特征被破坏了

**Comment by zhahuwangking** [comment]
> 1我训练的时候只用了voc12+07
> 2我也挺想知道的，我归结于keras的imagenet预训练权重更好
> 3可能是因为提取到的特征被破坏了
