### ISSUE TITLE
关于更新后的问题

### ISSUE THREAD

**Issue by zhahuwangking** [bubbliiiing/mobilenet-yolov4-lite-pytorch#5]
1、请问是重新训练了还是微调过了？（V2的map竟然达到了80多，之前还是70多。）
2、训练voc07+12的时候大神mosaic、cosine、smooth都使用了?（对于voc07+12来说smooth设置多少比较好？）
感谢打神！

**Comment by bubbliiiing** [comment]
1、重新训练，把正则化5e-4关了，并且改了letterbox_image
2、没使用
